version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mae-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      retries: 10
      timeout: 5s
    restart: unless-stopped

  mongo-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      bash -c "
      echo '⏳ Attente de MongoDB...' &&
      sleep 10 &&
      echo '🚀 Initialisation du Replica Set...' &&
      mongosh mongodb://mongo:27017 --eval '
        try {
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"localhost:27017\" }]
          });
        } catch (e) {
          print(\"⚠️ Déjà initialisé ou erreur : \" + e);
        }
      ' &&
      echo '✅ Replica Set prêt.'"
    restart: "no"

volumes:
  mongo_data: